name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"
  DB_NAME:
    description: "Database used"
    required: true
    default: "sandbox"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "rocket"
